/*=============================================================================
 * Program Name : EECS 348 Assignment 2 - CEO Inbox Email Prioritizer
 *
 * Description  : A C program that helps a busy company CEO decide which email
 *                to read next.  Emails are stored in a priority queue that is
 *                implemented from scratch as a MaxHeap kept in a dynamically
 *                sized list (a growable array).  The email with the highest
 *                priority always sits at the root of the heap, so the "next"
 *                email is always available in O(1) time, while inserting a new
 *                email or removing the read email costs O(log n) time.
 *
 *                Priority is decided first by the sender's category:
 *                    Boss            (read first, highest priority)
 *                    Subordinate
 *                    Peer
 *                    ImportantPerson
 *                    OtherPerson     (read last, lowest priority)
 *                When two emails come from the same category, the NEWEST email
 *                (the one with the later date) is read first.  If two emails
 *                also share the same date, the one that appeared later in the
 *                input file is treated as the newer of the two.
 *
 * Input        : A plain-text test file containing one command per line.  The
 *                file may be supplied either as a command-line argument
 *                    ./ceo_inbox testfile.txt
 *                or on standard input
 *                    ./ceo_inbox < testfile.txt
 *                Supported commands:
 *                    EMAIL <sender category>,<subject line>,<date>
 *                        Adds an email to the CEO's inbox.  <date> is MM-DD-YYYY
 *                        and <subject line> may contain spaces but not commas.
 *                    NEXT   - display the next email to read (does not remove it)
 *                    READ   - the CEO has read and dealt with the top email, so
 *                             remove it from the queue (displays nothing)
 *                    COUNT  - display the current count of unread emails
 *
 * Output       : Terminal output only.  COUNT prints
 *                    There are N emails to read.
 *                and NEXT prints
 *                    Next email:
 *                            Sender: <sender category>
 *                            Subject: <subject line>
 *                            Date: <MM-DD-YYYY>
 *                All diagnostics for bad input are written to stderr so that
 *                the normal program output on stdout stays clean and can be
 *                compared (diffed) against the expected output.
 *
 * Collaborators: None.
 *
 * Other sources: Code generated by two GenAI tools (see the GenAI analysis PDF
 *                that accompanies this assignment) was compared, one version
 *                was selected as the starting point, and it was then corrected,
 *                hardened, and re-commented by the author as required by the
 *                assignment.
 *
 * Author       : Erick Marte
 * Creation date: 09-17-2026
 * Revision date: 09-17-2026
 * Revisions    : 1. Replaced the fixed-size array from the generated code with
 *                   a dynamically grown list so the inbox has no hard limit.
 *                2. Added the newest-email-first tiebreak inside a sender
 *                   category, which the generated code did not implement.
 *                3. Added full input validation and error handling (bad file,
 *                   unknown command, malformed EMAIL line, unknown sender
 *                   category, invalid date, empty inbox, out-of-memory).
 *                4. Added prologue and per-line comments per the rubric.
 *===========================================================================*/

/* ---------------------------------------------------------------------------
 * Standard library headers.  Only the C standard library is used; no
 * pre-existing heap or priority-queue module is included, as required.
 * (Author-written block.)
 * ------------------------------------------------------------------------- */
#include <stdio.h>      /* printf, fprintf, fopen, fclose, fgetc, stdin       */
#include <stdlib.h>     /* malloc, realloc, free, EXIT_SUCCESS, EXIT_FAILURE  */
#include <string.h>     /* strcmp, strlen, memcpy                             */
#include <ctype.h>      /* isspace, isdigit                                   */

/* ---------------------------------------------------------------------------
 * Compile-time constants.  (Author-written block.)
 * ------------------------------------------------------------------------- */
#define SENDER_COUNT      5   /* how many sender categories the CEO knows about */
#define SENDER_TEXT_LEN  32   /* buffer size for a sender category string       */
#define DATE_TEXT_LEN    11   /* "MM-DD-YYYY" is 10 characters plus the NUL     */
#define INITIAL_CAPACITY  8   /* starting number of slots in the heap's list    */

/* ---------------------------------------------------------------------------
 * The five legal sender categories, written from the highest priority (index 0)
 * to the lowest priority (index SENDER_COUNT - 1).  Keeping them in one table
 * means the priority order is defined in exactly one place, which makes the
 * program easier to maintain.  (Author-written block.)
 * ------------------------------------------------------------------------- */
static const char *const SENDER_NAMES[SENDER_COUNT] = {
    "Boss",             /* read first                                          */
    "Subordinate",      /* read next                                           */
    "Peer",             /* read next                                           */
    "ImportantPerson",  /* read next                                           */
    "OtherPerson"       /* read last                                           */
};

/* ---------------------------------------------------------------------------
 * One email in the CEO's inbox.  (Author-written block.)
 * ------------------------------------------------------------------------- */
typedef struct {
    char  sender[SENDER_TEXT_LEN];  /* sender category exactly as it is printed  */
    char *subject;                  /* subject line, heap allocated, any length  */
    char  date[DATE_TEXT_LEN];      /* date normalized to MM-DD-YYYY for output  */
    long  dateKey;                  /* YYYYMMDD as a number, so dates compare    */
    long  arrival;                  /* order the email was read from the file    */
    int   rank;                     /* priority: 5 for Boss down to 1 for Other  */
} Email;

/* ---------------------------------------------------------------------------
 * The MaxHeap itself: a list (growable array) of emails plus its bookkeeping.
 * For the email stored at index i, its parent is at (i - 1) / 2 and its two
 * children are at 2i + 1 and 2i + 2.  (Author-written block.)
 * ------------------------------------------------------------------------- */
typedef struct {
    Email  *items;      /* the list of emails; items[0] is the highest priority  */
    size_t  count;      /* how many emails are currently stored in the list      */
    size_t  capacity;   /* how many emails the list can hold before it must grow */
} MaxHeap;

/* ---------------------------------------------------------------------------
 * Forward declarations so main() can be read before the helper functions.
 * (Author-written block.)
 * ------------------------------------------------------------------------- */
static void   heapInit(MaxHeap *heap);
static void   heapFree(MaxHeap *heap);
static int    heapPush(MaxHeap *heap, Email email);
static int    heapPop(MaxHeap *heap, Email *out);
static const Email *heapPeek(const MaxHeap *heap);
static void   heapSiftUp(MaxHeap *heap, size_t index);
static void   heapSiftDown(MaxHeap *heap, size_t index);
static int    emailHasHigherPriority(const Email *a, const Email *b);
static int    senderRank(const char *sender);
static int    parseDate(const char *text, char *normalized, long *key);
static char  *readLine(FILE *stream);
static char  *trimInPlace(char *text);
static void   processLine(MaxHeap *heap, char *line, long lineNumber, long *arrival);
static void   handleEmail(MaxHeap *heap, char *arguments, long lineNumber, long *arrival);
static void   handleNext(const MaxHeap *heap);
static void   handleRead(MaxHeap *heap, long lineNumber);
static void   handleCount(const MaxHeap *heap);
static void   beginOutputBlock(void);

/* ---------------------------------------------------------------------------
 * Tracks whether any output block has already been printed, so that the
 * program can place exactly one blank line BETWEEN blocks (and none before the
 * first block or after the last one), matching the sample output.
 * (Author-written block.)
 * ------------------------------------------------------------------------- */
static int g_blockPrinted = 0;

/*=============================================================================
 * Function : beginOutputBlock
 * Purpose  : Print the blank separator line that goes between output blocks.
 * Inputs   : none
 * Output   : a newline on stdout, except before the very first block
 *===========================================================================*/
static void beginOutputBlock(void)
{
    if (g_blockPrinted) {           /* if something was already printed ...     */
        putchar('\n');              /* ... separate the blocks with a blank line*/
    }
    g_blockPrinted = 1;             /* remember that a block has now been printed*/
}

/*=============================================================================
 * Function : heapInit
 * Purpose  : Put a MaxHeap into a valid, empty state.
 * Inputs   : heap - pointer to the heap to initialize
 * Output   : none (the heap is modified through the pointer)
 *===========================================================================*/
static void heapInit(MaxHeap *heap)
{
    heap->items    = NULL;          /* no list allocated yet; grown on first push*/
    heap->count    = 0;             /* the inbox starts out empty                */
    heap->capacity = 0;             /* and therefore has room for zero emails    */
}

/*=============================================================================
 * Function : heapFree
 * Purpose  : Release every block of memory the heap owns.
 * Inputs   : heap - pointer to the heap to destroy
 * Output   : none
 *===========================================================================*/
static void heapFree(MaxHeap *heap)
{
    size_t i;                                   /* loop counter over the list   */
    for (i = 0; i < heap->count; i++) {         /* visit every stored email     */
        free(heap->items[i].subject);           /* free that email's subject    */
    }
    free(heap->items);                          /* free the list itself         */
    heapInit(heap);                             /* reset to a valid empty state */
}

/*=============================================================================
 * Function : senderRank
 * Purpose  : Convert a sender category string into a numeric priority.
 * Inputs   : sender - the category text taken from the input file
 * Output   : 5 for Boss down to 1 for OtherPerson, or 0 if the text is not one
 *            of the five legal categories
 *===========================================================================*/
static int senderRank(const char *sender)
{
    int i;                                          /* index into SENDER_NAMES  */
    for (i = 0; i < SENDER_COUNT; i++) {            /* check each legal category*/
        if (strcmp(sender, SENDER_NAMES[i]) == 0) { /* exact match found?       */
            return SENDER_COUNT - i;                /* index 0 -> rank 5, etc.  */
        }
    }
    return 0;                                       /* 0 means "not a category" */
}

/*=============================================================================
 * Function : emailHasHigherPriority
 * Purpose  : Decide whether email a must be read before email b.  This single
 *            function defines the whole ordering of the priority queue.
 * Inputs   : a, b - pointers to the two emails being compared
 * Output   : 1 if a should be read before b, otherwise 0
 *===========================================================================*/
static int emailHasHigherPriority(const Email *a, const Email *b)
{
    if (a->rank != b->rank) {               /* different sender categories?      */
        return a->rank > b->rank;           /* the higher category wins          */
    }
    if (a->dateKey != b->dateKey) {         /* same category, different dates?   */
        return a->dateKey > b->dateKey;     /* the NEWER email wins              */
    }
    return a->arrival > b->arrival;         /* same date: later in file is newer */
}

/*=============================================================================
 * Function : heapSiftUp
 * Purpose  : Restore the heap property by moving the email at "index" up toward
 *            the root for as long as it outranks its parent.
 * Inputs   : heap  - the heap to repair
 *            index - position of the email that may be out of place
 * Output   : none (the list is reordered in place)
 *===========================================================================*/
static void heapSiftUp(MaxHeap *heap, size_t index)
{
    while (index > 0) {                                     /* stop at the root */
        size_t parent = (index - 1) / 2;                    /* parent position  */
        if (!emailHasHigherPriority(&heap->items[index],
                                    &heap->items[parent])) {/* parent still wins*/
            break;                                          /* heap is correct  */
        }
        {
            Email temp          = heap->items[parent];      /* classic 3-step   */
            heap->items[parent] = heap->items[index];       /* swap of the child*/
            heap->items[index]  = temp;                     /* and the parent   */
        }
        index = parent;                                     /* continue upward  */
    }
}

/*=============================================================================
 * Function : heapSiftDown
 * Purpose  : Restore the heap property by moving the email at "index" down
 *            toward the leaves for as long as a child outranks it.
 * Inputs   : heap  - the heap to repair
 *            index - position of the email that may be out of place
 * Output   : none (the list is reordered in place)
 *===========================================================================*/
static void heapSiftDown(MaxHeap *heap, size_t index)
{
    for (;;) {                                              /* loop until fixed */
        size_t left    = 2 * index + 1;                     /* left child index */
        size_t right   = 2 * index + 2;                     /* right child index*/
        size_t largest = index;                             /* best seen so far */

        if (left < heap->count &&                           /* left child exists*/
            emailHasHigherPriority(&heap->items[left],
                                   &heap->items[largest])) {/* and outranks it? */
            largest = left;                                 /* left is the best */
        }
        if (right < heap->count &&                          /* right child exists*/
            emailHasHigherPriority(&heap->items[right],
                                   &heap->items[largest])) {/* and outranks it? */
            largest = right;                                /* right is the best*/
        }
        if (largest == index) {                             /* parent wins?     */
            break;                                          /* heap is correct  */
        }
        {
            Email temp           = heap->items[largest];    /* swap the parent  */
            heap->items[largest] = heap->items[index];      /* with its stronger*/
            heap->items[index]   = temp;                    /* child            */
        }
        index = largest;                                    /* continue downward*/
    }
}

/*=============================================================================
 * Function : heapPush
 * Purpose  : Insert one email into the priority queue, growing the underlying
 *            list when it is full.
 * Inputs   : heap  - the heap to insert into
 *            email - the email to store (the heap takes ownership of subject)
 * Output   : 1 on success, 0 if memory could not be allocated
 *===========================================================================*/
static int heapPush(MaxHeap *heap, Email email)
{
    if (heap->count == heap->capacity) {                    /* the list is full */
        size_t newCapacity = (heap->capacity == 0)          /* first allocation?*/
                             ? INITIAL_CAPACITY             /* start small      */
                             : heap->capacity * 2;          /* otherwise double */
        Email *grown = (Email *)realloc(heap->items,        /* ask for a bigger */
                                        newCapacity * sizeof(Email)); /* block  */
        if (grown == NULL) {                                /* allocation failed*/
            return 0;                                       /* report failure   */
        }
        heap->items    = grown;                             /* keep the new list*/
        heap->capacity = newCapacity;                       /* and its new size */
    }
    heap->items[heap->count] = email;                       /* place at the end */
    heap->count++;                                          /* one more email   */
    heapSiftUp(heap, heap->count - 1);                      /* bubble it upward */
    return 1;                                               /* report success   */
}

/*=============================================================================
 * Function : heapPeek
 * Purpose  : Look at the highest priority email without removing it.
 * Inputs   : heap - the heap to inspect
 * Output   : pointer to the root email, or NULL when the inbox is empty
 *===========================================================================*/
static const Email *heapPeek(const MaxHeap *heap)
{
    if (heap->count == 0) {         /* nothing stored?                          */
        return NULL;                /* tell the caller the inbox is empty       */
    }
    return &heap->items[0];         /* the root is always the next email        */
}

/*=============================================================================
 * Function : heapPop
 * Purpose  : Remove the highest priority email from the queue.
 * Inputs   : heap - the heap to remove from
 *            out  - optional destination for the removed email; pass NULL to
 *                   have the email discarded and its memory freed here
 * Output   : 1 if an email was removed, 0 if the inbox was already empty
 *===========================================================================*/
static int heapPop(MaxHeap *heap, Email *out)
{
    Email top;                                      /* copy of the root email   */
    if (heap->count == 0) {                         /* nothing to remove?       */
        return 0;                                   /* report the empty inbox   */
    }
    top = heap->items[0];                           /* save the highest priority*/
    heap->count--;                                  /* the list is one shorter  */
    if (heap->count > 0) {                          /* emails still remain?     */
        heap->items[0] = heap->items[heap->count];  /* move the last to the root*/
        heapSiftDown(heap, 0);                      /* and push it back down    */
    }
    if (out != NULL) {                              /* caller wants the email?  */
        *out = top;                                 /* hand over ownership      */
    } else {                                        /* caller does not want it  */
        free(top.subject);                          /* so free its subject here */
    }
    return 1;                                       /* report success           */
}

/*=============================================================================
 * Function : trimInPlace
 * Purpose  : Remove leading and trailing whitespace from a string.
 * Inputs   : text - the modifiable string to trim
 * Output   : pointer to the first non-space character (the string is also
 *            terminated early to drop trailing spaces)
 *===========================================================================*/
static char *trimInPlace(char *text)
{
    char *end;                                              /* walks backward   */
    while (*text != '\0' && isspace((unsigned char)*text)) { /* leading spaces   */
        text++;                                             /* skip past them   */
    }
    if (*text == '\0') {                                    /* all whitespace?  */
        return text;                                        /* empty string     */
    }
    end = text + strlen(text) - 1;                          /* last character   */
    while (end > text && isspace((unsigned char)*end)) {     /* trailing spaces  */
        *end = '\0';                                        /* cut them off     */
        end--;                                              /* keep walking back*/
    }
    return text;                                            /* trimmed string   */
}

/*=============================================================================
 * Function : parseDate
 * Purpose  : Validate a date written as MM-DD-YYYY and convert it into both a
 *            normalized printable string and a sortable number.
 * Inputs   : text       - the date text from the input file
 *            normalized - buffer of DATE_TEXT_LEN bytes for the printable form
 *            key        - destination for the sortable value YYYYMMDD
 * Output   : 1 if the date is valid, 0 if it is malformed or impossible
 *===========================================================================*/
static int parseDate(const char *text, char *normalized, long *key)
{
    int  month = 0, day = 0, year = 0;                  /* the three date parts */
    int  i;                                             /* digit loop counter   */
    int  daysInMonth;                                   /* length of that month */
    const int monthLengths[12] =                        /* days per month, with */
        { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }; /* February as 28   */

    for (i = 0; i < 10; i++) {                          /* MM-DD-YYYY is 10 wide*/
        if (text[i] == '\0') {                          /* string ended early?  */
            return 0;                                   /* malformed date       */
        }
        if (i == 2 || i == 5) {                         /* positions of dashes  */
            if (text[i] != '-') {                       /* dash missing?        */
                return 0;                               /* malformed date       */
            }
        } else if (!isdigit((unsigned char)text[i])) {  /* every other spot is a*/
            return 0;                                   /* digit, or it is bad  */
        }
    }
    if (text[10] != '\0') {                             /* extra trailing text? */
        return 0;                                       /* malformed date       */
    }

    month = (text[0] - '0') * 10 + (text[1] - '0');      /* characters to number */
    day   = (text[3] - '0') * 10 + (text[4] - '0');      /* characters to number */
    year  = (text[6] - '0') * 1000 + (text[7] - '0') * 100  /* four digit year   */
          + (text[8] - '0') * 10   + (text[9] - '0');

    if (month < 1 || month > 12) {                      /* month out of range?  */
        return 0;                                       /* reject the date      */
    }
    if (year < 1) {                                     /* year 0000 is not real*/
        return 0;                                       /* reject the date      */
    }
    daysInMonth = monthLengths[month - 1];              /* normal month length  */
    if (month == 2 &&                                   /* February needs the   */
        ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0)) { /* leap rule */
        daysInMonth = 29;                               /* leap year February   */
    }
    if (day < 1 || day > daysInMonth) {                 /* day out of range?    */
        return 0;                                       /* reject the date      */
    }

    memcpy(normalized, text, 10);                       /* the text is already  */
    normalized[10] = '\0';                              /* exactly MM-DD-YYYY   */
    *key = (long)year * 10000L + (long)month * 100L + (long)day; /* sortable    */
    return 1;                                           /* the date is valid    */
}

/*=============================================================================
 * Function : readLine
 * Purpose  : Read one line of any length from a stream into fresh memory, so
 *            that a very long subject line can never overflow a fixed buffer.
 * Inputs   : stream - the already open file or stdin
 * Output   : a malloc'd string without its newline, which the caller frees, or
 *            NULL at end of file or on an allocation failure
 *===========================================================================*/
static char *readLine(FILE *stream)
{
    size_t  capacity = 128;                         /* starting buffer size     */
    size_t  length   = 0;                           /* characters stored so far */
    char   *buffer   = (char *)malloc(capacity);    /* first buffer allocation  */
    int     ch;                                     /* one character from input */

    if (buffer == NULL) {                           /* allocation failed?       */
        return NULL;                                /* caller sees end of input */
    }
    ch = fgetc(stream);                             /* read the first character */
    if (ch == EOF) {                                /* nothing left in the file?*/
        free(buffer);                               /* release the buffer       */
        return NULL;                                /* signal end of file       */
    }
    while (ch != EOF && ch != '\n') {               /* until newline or EOF     */
        if (length + 1 >= capacity) {               /* buffer nearly full?      */
            char *grown = (char *)realloc(buffer, capacity * 2); /* double it   */
            if (grown == NULL) {                    /* out of memory?           */
                free(buffer);                       /* release what we had      */
                return NULL;                        /* signal failure           */
            }
            buffer   = grown;                       /* keep the larger buffer   */
            capacity *= 2;                          /* remember the new size    */
        }
        buffer[length] = (char)ch;                  /* store the character      */
        length++;                                   /* one more character       */
        ch = fgetc(stream);                         /* read the next character  */
    }
    if (length > 0 && buffer[length - 1] == '\r') { /* Windows line ending?     */
        length--;                                   /* drop the carriage return */
    }
    buffer[length] = '\0';                          /* terminate the string     */
    return buffer;                                  /* caller owns this memory  */
}

/*=============================================================================
 * Function : handleEmail
 * Purpose  : Validate one EMAIL command and, if it is well formed, add the new
 *            email to the priority queue.
 * Inputs   : heap       - the priority queue to insert into
 *            arguments  - the text after the EMAIL keyword
 *            lineNumber - line of the input file, used in error messages
 *            arrival    - running counter used to break exact-date ties
 * Output   : none on stdout; a diagnostic on stderr when the line is rejected
 *===========================================================================*/
static void handleEmail(MaxHeap *heap, char *arguments, long lineNumber, long *arrival)
{
    char  *firstComma;                              /* separates sender/subject */
    char  *lastComma;                               /* separates subject/date   */
    char  *senderText;                              /* trimmed sender category  */
    char  *subjectText;                             /* trimmed subject line     */
    char  *dateText;                                /* trimmed date text        */
    Email  email;                                   /* the email being built    */
    int    rank;                                    /* priority of the sender   */
    size_t subjectLength;                           /* length of subject line   */

    firstComma = strchr(arguments, ',');            /* find the first comma     */
    lastComma  = strrchr(arguments, ',');           /* find the last comma      */
    if (firstComma == NULL || lastComma == firstComma) { /* fewer than 2 commas */
        fprintf(stderr,
                "Error (line %ld): EMAIL needs the form "
                "EMAIL <sender>,<subject>,<date>. Line ignored.\n", lineNumber);
        return;                                     /* skip this bad line       */
    }
    if (strchr(firstComma + 1, ',') != lastComma) { /* more than two commas?    */
        fprintf(stderr,
                "Error (line %ld): subject line may not contain a comma. "
                "Line ignored.\n", lineNumber);
        return;                                     /* skip this bad line       */
    }

    *firstComma = '\0';                             /* cut the sender loose     */
    *lastComma  = '\0';                             /* cut the date loose       */
    senderText  = trimInPlace(arguments);           /* sender without spaces    */
    subjectText = trimInPlace(firstComma + 1);      /* subject without spaces   */
    dateText    = trimInPlace(lastComma + 1);       /* date without spaces      */

    rank = senderRank(senderText);                  /* look up the priority     */
    if (rank == 0) {                                /* not one of the five?     */
        fprintf(stderr,
                "Error (line %ld): unknown sender category \"%s\". "
                "Line ignored.\n", lineNumber, senderText);
        return;                                     /* skip this bad line       */
    }
    if (subjectText[0] == '\0') {                   /* empty subject line?      */
        fprintf(stderr,
                "Error (line %ld): the subject line is empty. Line ignored.\n",
                lineNumber);
        return;                                     /* skip this bad line       */
    }
    if (!parseDate(dateText, email.date, &email.dateKey)) { /* validate the date*/
        fprintf(stderr,
                "Error (line %ld): invalid date \"%s\", expected MM-DD-YYYY. "
                "Line ignored.\n", lineNumber, dateText);
        return;                                     /* skip this bad line       */
    }

    subjectLength   = strlen(subjectText);          /* size needed for a copy   */
    email.subject   = (char *)malloc(subjectLength + 1); /* room for the subject*/
    if (email.subject == NULL) {                    /* out of memory?           */
        fprintf(stderr,
                "Error (line %ld): out of memory storing the subject line. "
                "Line ignored.\n", lineNumber);
        return;                                     /* skip this line safely    */
    }
    memcpy(email.subject, subjectText, subjectLength + 1); /* copy the subject  */

    /* The sender text is already known to be one of the five short category
     * names, so it always fits in the fixed sender buffer. (Author-written.) */
    strcpy(email.sender, SENDER_NAMES[SENDER_COUNT - rank]); /* canonical name  */
    email.rank      = rank;                         /* store the priority       */
    email.arrival   = *arrival;                     /* store the arrival order  */
    (*arrival)++;                                   /* next email is newer      */

    if (!heapPush(heap, email)) {                   /* insert into the queue    */
        fprintf(stderr,
                "Error (line %ld): out of memory growing the inbox. "
                "Line ignored.\n", lineNumber);
        free(email.subject);                        /* the heap never took it   */
    }
}

/*=============================================================================
 * Function : handleNext
 * Purpose  : Display the next email the CEO should read, leaving it in the
 *            queue so that two NEXT commands in a row print the same email.
 * Inputs   : heap - the priority queue to inspect
 * Output   : the email block, or a notice that the inbox is empty
 *===========================================================================*/
static void handleNext(const MaxHeap *heap)
{
    const Email *next = heapPeek(heap);             /* highest priority email   */
    beginOutputBlock();                             /* blank line between blocks*/
    if (next == NULL) {                             /* inbox is empty?          */
        printf("There are no emails to read.\n");   /* say so instead of crashing*/
        return;                                     /* nothing else to print    */
    }
    printf("Next email:\n");                        /* header line              */
    printf("\tSender: %s\n",  next->sender);        /* the sender category      */
    printf("\tSubject: %s\n", next->subject);       /* the subject line         */
    printf("\tDate: %s\n",    next->date);          /* the date, MM-DD-YYYY     */
}

/*=============================================================================
 * Function : handleRead
 * Purpose  : Record that the CEO has read and dealt with the highest priority
 *            email by removing it from the queue.  Nothing is displayed, so two
 *            READs in a row simply delete the top two emails.
 * Inputs   : heap       - the priority queue to remove from
 *            lineNumber - line of the input file, used in the error message
 * Output   : none on stdout; a diagnostic on stderr if the inbox is empty
 *===========================================================================*/
static void handleRead(MaxHeap *heap, long lineNumber)
{
    if (!heapPop(heap, NULL)) {                     /* try to drop the top email*/
        fprintf(stderr,
                "Warning (line %ld): READ was given but the inbox is empty.\n",
                lineNumber);                        /* warn without stopping    */
    }
}

/*=============================================================================
 * Function : handleCount
 * Purpose  : Display how many unread emails remain in the CEO's inbox.
 * Inputs   : heap - the priority queue to count
 * Output   : one line of the form "There are N emails to read."
 *===========================================================================*/
static void handleCount(const MaxHeap *heap)
{
    beginOutputBlock();                             /* blank line between blocks*/
    printf("There are %lu emails to read.\n",       /* the required wording     */
           (unsigned long)heap->count);             /* current number of emails */
}

/*=============================================================================
 * Function : processLine
 * Purpose  : Identify which command a single input line holds and dispatch it.
 * Inputs   : heap       - the priority queue the command acts on
 *            line       - the modifiable text of the line
 *            lineNumber - line of the input file, used in error messages
 *            arrival    - running counter used to break exact-date ties
 * Output   : whatever the dispatched command prints
 *===========================================================================*/
static void processLine(MaxHeap *heap, char *line, long lineNumber, long *arrival)
{
    char *text = trimInPlace(line);                 /* drop surrounding spaces  */
    if (text[0] == '\0') {                          /* a blank line?            */
        return;                                     /* silently ignore it       */
    }

    if (strncmp(text, "EMAIL", 5) == 0 &&           /* starts with the keyword  */
        (text[5] == ' ' || text[5] == '\t')) {      /* followed by a separator  */
        handleEmail(heap, text + 6, lineNumber, arrival); /* parse the rest     */
    } else if (strcmp(text, "NEXT") == 0) {         /* the NEXT command         */
        handleNext(heap);                           /* show the next email      */
    } else if (strcmp(text, "READ") == 0) {         /* the READ command         */
        handleRead(heap, lineNumber);               /* remove the top email     */
    } else if (strcmp(text, "COUNT") == 0) {        /* the COUNT command        */
        handleCount(heap);                          /* print the unread count   */
    } else if (strcmp(text, "EMAIL") == 0) {        /* EMAIL with no arguments  */
        fprintf(stderr,
                "Error (line %ld): EMAIL is missing its arguments. "
                "Line ignored.\n", lineNumber);
    } else {                                        /* anything else is unknown */
        fprintf(stderr,
                "Error (line %ld): unrecognized command \"%s\". Line ignored.\n",
                lineNumber, text);
    }
}

/*=============================================================================
 * Function : main
 * Purpose  : Open the test file (or fall back to standard input), run every
 *            command in it against the priority queue, then clean up.
 * Inputs   : argc, argv - an optional single command-line argument naming the
 *                         test file
 * Output   : the program's terminal output; exit status EXIT_SUCCESS on a clean
 *            run and EXIT_FAILURE when the file could not be used
 *===========================================================================*/
int main(int argc, char *argv[])
{
    MaxHeap  inbox;                                 /* the CEO's priority queue */
    FILE    *input      = stdin;                    /* default source of commands*/
    int      usingFile  = 0;                        /* remembers to fclose later*/
    long     lineNumber = 0;                        /* counts lines for messages*/
    long     arrival    = 0;                        /* counts emails for ties   */
    char    *line;                                  /* one line of input        */

    if (argc > 2) {                                 /* too many arguments?      */
        fprintf(stderr, "Usage: %s [testfile]\n", argv[0]); /* show correct use */
        return EXIT_FAILURE;                        /* stop with an error status*/
    }
    if (argc == 2) {                                /* a file name was given    */
        input = fopen(argv[1], "r");                /* try to open it for reading*/
        if (input == NULL) {                        /* the file is missing or   */
            fprintf(stderr,                         /* cannot be read           */
                    "Error: cannot open input file \"%s\".\n", argv[1]);
            return EXIT_FAILURE;                    /* stop with an error status*/
        }
        usingFile = 1;                              /* remember to close it     */
    }

    heapInit(&inbox);                               /* start with an empty inbox*/

    while ((line = readLine(input)) != NULL) {      /* read every line of input */
        lineNumber++;                               /* count the line for errors*/
        if (lineNumber == 1 &&                      /* a UTF-8 byte order mark  */
            (unsigned char)line[0] == 0xEF &&       /* can appear at the start  */
            (unsigned char)line[1] == 0xBB &&       /* of files saved by some   */
            (unsigned char)line[2] == 0xBF) {       /* editors; skip it so the  */
            processLine(&inbox, line + 3, lineNumber, &arrival); /* first command
                                                     * is still recognized      */
        } else {
            processLine(&inbox, line, lineNumber, &arrival); /* normal dispatch */
        }
        free(line);                                 /* release the line buffer  */
    }

    if (lineNumber == 0) {                          /* the input held no lines  */
        fprintf(stderr, "Warning: the input contained no commands.\n");
    }

    heapFree(&inbox);                               /* free every stored email  */
    if (usingFile) {                                /* did we open a real file? */
        fclose(input);                              /* then close it politely   */
    }
    return EXIT_SUCCESS;                            /* finished successfully    */
}
