/*=============================================================================
 * Name of Program : EECS 348 Assignment 2 - CEO Email Priority Queue
 *
 * Brief Description:
 *   Implements a priority queue as a list-based MaxHeap to decide which email
 *   a busy company CEO should read next.  Emails are ordered first by sender
 *   category (Boss > Subordinate > Peer > ImportantPerson > OtherPerson) and,
 *   within a category, newest date first.  Commands EMAIL, NEXT, READ and
 *   COUNT are processed from a test file, and every malformed line is reported
 *   and skipped rather than being allowed to corrupt the queue.
 *
 * Inputs :
 *   A plain-text test file, supplied either as a command-line argument
 *       ./ceo_inbox testfile.txt
 *   or on standard input
 *       ./ceo_inbox < testfile.txt
 *   Commands:
 *       EMAIL <sender category>,<subject line>,<date>   add an email
 *       NEXT    display the next email to read (leaves it in the queue)
 *       READ    the CEO dealt with the top email; remove it, display nothing
 *       COUNT   display the current count of unread emails
 *
 * Output :
 *   Terminal output on stdout.  Diagnostics for bad input go to stderr so the
 *   program output stays clean enough to diff against the expected output.
 *
 * All Collaborators : Myself and Gemini and Claude
 *
 * Other Sources :
 *   Base implementation generated by Gemini (see the GenAI analysis PDF that
 *   accompanies this assignment).  The generated version was measured and
 *   profiled, then corrected and optimized by the author; every change is
 *   listed under "Revisions" below and marked in the code with the comment
 *   tag [CHANGED] or [ADDED].  Blocks carrying neither tag are substantially
 *   as generated.
 *
 * Author's Full Name : Erick Marte
 * Creation Date  : September 17, 2026
 * Revision Date  : September 17, 2026
 *
 * Revisions (improvements over the generated code):
 *   CORRECTNESS
 *     R1. Output now matches the required format exactly: the Sender, Subject
 *         and Date lines are tab-indented and output blocks are separated by a
 *         blank line.  The generated version printed the right emails in the
 *         right order but failed a diff on every line.
 *     R2. Dates are validated strictly.  The generated code used
 *         sscanf("%d-%d-%d"), which accepted the impossible date 02-31-2024,
 *         accepted trailing junk such as 12-25-2024XYZ, and echoed unpadded
 *         input such as 1-3-2025 straight back out.  Dates are now checked
 *         character by character, range checked per month, leap-year aware,
 *         and always printed in normalized MM-DD-YYYY form.
 *     R3. Replaced strcasecmp, which is POSIX rather than standard C and was
 *         used without including <strings.h>.  It compiled only by accident in
 *         GCC's default mode, warned under -std=c11 -pedantic, and is a hard
 *         error under GCC 14 and newer.  Category lookup now uses a four-line
 *         equals_ignore_case helper written in standard C, which keeps the
 *         case-insensitive matching while compiling anywhere.
 *     R4. Fixed a latent buffer overflow in heap_insert: the generated code
 *         executed capacity *= 2 BEFORE checking that realloc succeeded, so a
 *         failed reallocation left the heap believing it had twice the room it
 *         actually had, and every later insert wrote past the end of the array.
 *     R5. Input lines are read into memory that grows as needed.  The 512-byte
 *         fgets buffer silently split any longer line in two, losing the email
 *         and emitting a bogus "unrecognized command" for the remainder.
 *     R6. heap_peek_max and heap_extract_max now check for an empty heap
 *         themselves instead of trusting the caller to check first.
 *     R7. Rejects an EMAIL line carrying more than two commas instead of
 *         silently dropping the extra fields, and rejects an empty subject.
 *     R8. Accepts the test file as a command-line argument as well as on
 *         standard input; the generated version read stdin only.
 *   SPACE COMPLEXITY
 *     R9. sizeof(Email) reduced from 356 bytes to 32 bytes.  The subject is
 *         now a right-sized allocation instead of a fixed char[256]; the
 *         sender category is recovered from the priority rank through the
 *         SENDER_NAMES table instead of storing a separate char[64] copy of a
 *         string the program already knows; and the date is stored only as the
 *         sortable long it is compared on, with the printable form rebuilt on
 *         demand rather than kept as a second char[16] copy.
 *   EXECUTION TIME
 *    R10. Replaced the three-assignment swap in both sift loops with the
 *         standard hole technique: the element being moved is saved once, the
 *         elements it passes are shifted into the hole, and it is written back
 *         a single time at the end.  This performs one element copy per level
 *         of the tree instead of three, and combined with R9 it cuts the bytes
 *         moved per level from 1068 to 32.
 *   MAINTAINABILITY
 *    R11. The priority order now lives in exactly one ordered table
 *         (SENDER_NAMES) and the rank is derived from the array index, so
 *         adding a category is a one-line edit.  The generated code spread the
 *         order across five if statements with the magic numbers 5..1 inline.
 *    R12. Heap functions report failure through return values instead of
 *         calling exit(), so the heap is reusable and testable rather than
 *         being allowed to terminate the whole program from inside a library
 *         routine.
 *    R13. The heap control block is a plain struct the caller owns rather than
 *         a second heap allocation, which removes one malloc, one free and one
 *         pointer indirection per access.
 *===========================================================================*/

/* ---------------------------------------------------------------------------
 * Standard library headers.  Only the C standard library is used; no
 * pre-existing heap or priority-queue module is included, as required.
 * [CHANGED] <strings.h> is no longer needed because strcasecmp is gone (R3).
 * ------------------------------------------------------------------------- */
#include <stdio.h>      /* printf, fprintf, fopen, fclose, fgetc, stdin      */
#include <stdlib.h>     /* malloc, realloc, free, EXIT_SUCCESS, EXIT_FAILURE */
#include <string.h>     /* strcmp, strchr, strrchr, strlen, memcpy           */
#include <ctype.h>      /* isspace, isdigit                                  */

/* ---------------------------------------------------------------------------
 * Compile-time constants.
 * [CHANGED] MAX_LINE_LEN is gone; lines are read into memory that grows (R5).
 * ------------------------------------------------------------------------- */
#define SENDER_COUNT      5   /* how many sender categories exist             */
#define INITIAL_CAPACITY 10   /* starting number of slots in the heap's list  */
#define DATE_BUFFER_LEN  16   /* scratch space for a printable MM-DD-YYYY date*/

/* ---------------------------------------------------------------------------
 * [CHANGED] (R11) The five sender categories in priority order, highest first.
 * This single table replaces the chain of if statements in the generated code.
 * A category's rank is derived from its index as SENDER_COUNT - index, so
 * index 0 (Boss) is rank 5 and index 4 (OtherPerson) is rank 1.  Because the
 * rank determines the index, the rank alone is enough to recover the category
 * name for printing, which is what lets the Email struct drop its char[64]
 * sender field entirely (R9).
 * ------------------------------------------------------------------------- */
static const char *const SENDER_NAMES[SENDER_COUNT] = {
    "Boss",             /* rank 5, read first                                 */
    "Subordinate",      /* rank 4, read next                                  */
    "Peer",             /* rank 3, read next                                  */
    "ImportantPerson",  /* rank 2, read next                                  */
    "OtherPerson"       /* rank 1, read last                                  */
};

/* ---------------------------------------------------------------------------
 * [ADDED] Spelling variants accepted for two of the categories, kept from the
 * generated code's leniency.  They map to a rank; the canonical spelling in
 * SENDER_NAMES is what gets printed, so output stays consistent either way.
 * ------------------------------------------------------------------------- */
typedef struct {
    const char *text;   /* the alternative spelling that may appear in input  */
    int         rank;   /* the rank that spelling maps to                     */
} CategoryAlias;

static const CategoryAlias CATEGORY_ALIASES[] = {
    { "Important Person", 2 },  /* spaced spelling of ImportantPerson         */
    { "Other Person",     1 }   /* spaced spelling of OtherPerson             */
};

#define ALIAS_COUNT (sizeof(CATEGORY_ALIASES) / sizeof(CATEGORY_ALIASES[0]))

/* ---------------------------------------------------------------------------
 * [CHANGED] (R9) One email in the CEO's inbox, reduced from 356 bytes to 32.
 *
 *   Generated version                    This version
 *   -----------------------------------  ---------------------------------
 *   char sender[64];                     (recovered from rank)
 *   char subject[256];                   char *subject  (right-sized)
 *   char date[16];                       (rebuilt from date_key)
 *   int year, month, day;                long date_key  (YYYYMMDD)
 *   int category_priority;               int rank
 *   int sequence_id;                     long sequence
 *
 * Nothing is lost: the sender name is SENDER_NAMES[SENDER_COUNT - rank], and
 * the printable date is rebuilt from date_key by format_date below.
 * ------------------------------------------------------------------------- */
typedef struct {
    char *subject;      /* subject line, heap allocated to its actual length  */
    long  date_key;     /* the date as YYYYMMDD, which is also its sort order */
    long  sequence;     /* arrival order, used to break exact-date ties       */
    int   rank;         /* 5 for Boss down to 1 for OtherPerson               */
} Email;

/* ---------------------------------------------------------------------------
 * The list-based MaxHeap.  For the email at index i the parent is (i - 1) / 2
 * and the children are 2i + 1 and 2i + 2.
 * [CHANGED] (R13) The caller owns this struct, so the generated code's second
 * malloc for the control block is gone.  Sizes are size_t rather than int, so
 * the counts cannot overflow before memory does.
 * ------------------------------------------------------------------------- */
typedef struct {
    Email  *data;       /* the list of emails; data[0] is the highest priority*/
    size_t  size;       /* how many emails are currently stored               */
    size_t  capacity;   /* how many the list can hold before it must grow     */
} MaxHeap;

/* ---------------------------------------------------------------------------
 * Function prototypes.
 * [CHANGED] (R12) heap_insert and heap_extract_max return a status instead of
 * calling exit(); heap_peek_max returns a pointer so it can report emptiness.
 * ------------------------------------------------------------------------- */
static void  heap_init(MaxHeap *heap);
static void  heap_destroy(MaxHeap *heap);
static int   heap_insert(MaxHeap *heap, Email email);
static int   heap_extract_max(MaxHeap *heap, Email *out);
static const Email *heap_peek_max(const MaxHeap *heap);
static int   compare_emails(const Email *e1, const Email *e2);
static int   equals_ignore_case(const char *a, const char *b);
static int   get_category_priority(const char *category);
static void  format_date(long date_key, char *buffer);
static int   parse_date(const char *date_str, long *key);
static char *trim_whitespace(char *str);
static char *read_line(FILE *stream);
static void  handle_email_command(MaxHeap *heap, char *args, long line_no, long *sequence);
static void  handle_next_command(const MaxHeap *heap);
static void  handle_read_command(MaxHeap *heap, long line_no);
static void  handle_count_command(const MaxHeap *heap);
static void  process_line(MaxHeap *heap, char *line, long line_no, long *sequence);
static void  begin_output_block(void);

/* ---------------------------------------------------------------------------
 * [ADDED] (R1) Remembers whether an output block has already been printed, so
 * exactly one blank line separates blocks, with none before the first block or
 * after the last.  This is what makes the output match the assignment sample.
 * ------------------------------------------------------------------------- */
static int g_block_printed = 0;

/*=============================================================================
 * Block: Output Formatting
 *=============================================================================
 * Function : begin_output_block
 * Purpose  : Print the blank separator that belongs between output blocks.
 * Inputs   : none
 * Output   : a newline on stdout, except before the very first block
 *===========================================================================*/
static void begin_output_block(void)
{
    if (g_block_printed) {              /* something was printed already?     */
        putchar('\n');                  /* separate the blocks with a blank   */
    }
    g_block_printed = 1;                /* a block has now been printed       */
}

/*=============================================================================
 * Block: Utility Helper Functions
 *=============================================================================
 * Function : trim_whitespace
 * Purpose  : Remove leading and trailing whitespace from a string.
 * Inputs   : str - the modifiable string to trim
 * Output   : pointer to the first non-space character; trailing spaces are
 *            overwritten with a terminator
 *
 * [CHANGED] The generated version used memmove to shift the whole string back
 * to the start of the buffer, which is O(length) work for no benefit.  This
 * version returns a pointer to the first useful character instead, which is
 * O(1) and never touches the leading bytes.
 *===========================================================================*/
static char *trim_whitespace(char *str)
{
    char *end;                                          /* walks backward     */
    if (str == NULL) {                                  /* null pointer guard */
        return NULL;                                    /* nothing to trim    */
    }
    while (*str != '\0' && isspace((unsigned char)*str)) { /* leading spaces  */
        str++;                                          /* skip past them     */
    }
    if (*str == '\0') {                                 /* all whitespace?    */
        return str;                                     /* an empty string    */
    }
    end = str + strlen(str) - 1;                        /* last character     */
    while (end > str && isspace((unsigned char)*end)) { /* trailing spaces    */
        *end = '\0';                                    /* cut them off       */
        end--;                                          /* keep walking back  */
    }
    return str;                                         /* the trimmed string */
}

/*=============================================================================
 * Function : equals_ignore_case
 * Purpose  : Compare two strings without regard to letter case.
 * Inputs   : a, b - the two strings to compare
 * Output   : 1 if they match ignoring case, otherwise 0
 *
 * [ADDED] (R3) The generated code got case-insensitive matching from
 * strcasecmp, which is a POSIX extension rather than standard C and was used
 * without including <strings.h>.  It compiled only because GCC's default gnu
 * mode exposes it; it warns under -std=c11 -pedantic and is a hard error under
 * GCC 14 and newer.  This four-line helper keeps the useful leniency while
 * using nothing outside the C standard library, so it compiles anywhere.
 *===========================================================================*/
static int equals_ignore_case(const char *a, const char *b)
{
    while (*a != '\0' && *b != '\0') {                      /* until either end*/
        if (tolower((unsigned char)*a) !=                   /* compare folded */
            tolower((unsigned char)*b)) {                   /* to lower case  */
            return 0;                                       /* they differ    */
        }
        a++;                                                /* advance both   */
        b++;                                                /* in step        */
    }
    return (*a == '\0' && *b == '\0');                      /* both ended?    */
}

/*=============================================================================
 * Function : get_category_priority
 * Purpose  : Convert a sender category string into its numeric priority.
 * Inputs   : category - the category text taken from the input file
 * Output   : 5 for Boss down to 1 for OtherPerson, or 0 if unrecognized
 *
 * [CHANGED] (R3, R11) Walks the single ordered SENDER_NAMES table instead of
 * five hard-coded comparisons, and uses the portable helper above rather than
 * strcasecmp.  Matching stays case-insensitive, but whatever case the input
 * used, the canonical spelling from SENDER_NAMES is what gets printed.
 *===========================================================================*/
static int get_category_priority(const char *category)
{
    int i;                                                  /* loop counter   */
    if (category == NULL) {                                 /* null guard     */
        return 0;                                           /* unrecognized   */
    }
    for (i = 0; i < SENDER_COUNT; i++) {                    /* canonical names*/
        if (equals_ignore_case(category, SENDER_NAMES[i])) { /* a match?      */
            return SENDER_COUNT - i;                        /* index -> rank  */
        }
    }
    for (i = 0; i < (int)ALIAS_COUNT; i++) {                /* spelling aliases*/
        if (equals_ignore_case(category, CATEGORY_ALIASES[i].text)) { /* match*/
            return CATEGORY_ALIASES[i].rank;                /* its rank       */
        }
    }
    return 0;                                               /* not a category */
}

/*=============================================================================
 * Function : format_date
 * Purpose  : Rebuild the printable MM-DD-YYYY text from the stored sort key.
 * Inputs   : date_key - the date encoded as YYYYMMDD
 *            buffer   - at least DATE_BUFFER_LEN bytes of scratch space
 * Output   : buffer holds the normalized date text
 *
 * [ADDED] (R9) This is what lets the Email struct drop its char[16] date
 * field: the printable form is derived when it is needed rather than stored
 * alongside the value it is derived from.
 *===========================================================================*/
static void format_date(long date_key, char *buffer)
{
    int year  = (int)(date_key / 10000L);           /* top four digits        */
    int month = (int)((date_key / 100L) % 100L);    /* middle two digits      */
    int day   = (int)(date_key % 100L);             /* bottom two digits      */
    sprintf(buffer, "%02d-%02d-%04d", month, day, year); /* required ordering */
}

/*=============================================================================
 * Function : parse_date
 * Purpose  : Validate a date written as MM-DD-YYYY and convert it to the
 *            sortable value YYYYMMDD.
 * Inputs   : date_str - the date text from the input file
 *            key      - destination for the sortable value
 * Output   : 1 if the date is valid, 0 if it is malformed or impossible
 *
 * [CHANGED] (R2) The generated version called sscanf("%d-%d-%d") and then
 * range checked the day against 31 for every month.  That accepted
 * 02-31-2024, accepted trailing junk because sscanf stops at the last field it
 * matched, and accepted 1-3-2025 which was then printed back unpadded.  This
 * version checks the exact ten-character shape, then range checks the day
 * against the real length of that month, including leap Februaries.
 *===========================================================================*/
static int parse_date(const char *date_str, long *key)
{
    int month, day, year;                               /* the three parts    */
    int i;                                              /* digit loop counter */
    int days_in_month;                                  /* real month length  */
    const int MONTH_LENGTHS[12] =                       /* days per month,    */
        { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }; /* Feb as 28      */

    if (date_str == NULL || key == NULL) {              /* null pointer guard */
        return 0;                                       /* reject the date    */
    }
    for (i = 0; i < 10; i++) {                          /* MM-DD-YYYY is 10   */
        if (date_str[i] == '\0') {                      /* string ended early?*/
            return 0;                                   /* reject the date    */
        }
        if (i == 2 || i == 5) {                         /* the dash positions */
            if (date_str[i] != '-') {                   /* dash missing?      */
                return 0;                               /* reject the date    */
            }
        } else if (!isdigit((unsigned char)date_str[i])) { /* all else digits */
            return 0;                                   /* reject the date    */
        }
    }
    if (date_str[10] != '\0') {                         /* trailing junk?     */
        return 0;                                       /* reject the date    */
    }

    month = (date_str[0] - '0') * 10 + (date_str[1] - '0');  /* chars to int  */
    day   = (date_str[3] - '0') * 10 + (date_str[4] - '0');  /* chars to int  */
    year  = (date_str[6] - '0') * 1000 + (date_str[7] - '0') * 100
          + (date_str[8] - '0') * 10   + (date_str[9] - '0');

    if (month < 1 || month > 12) {                      /* impossible month?  */
        return 0;                                       /* reject the date    */
    }
    if (year < 1) {                                     /* year 0000?         */
        return 0;                                       /* reject the date    */
    }
    days_in_month = MONTH_LENGTHS[month - 1];           /* normal length      */
    if (month == 2 &&                                   /* February needs the */
        ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0)) { /* leap rule*/
        days_in_month = 29;                             /* leap February      */
    }
    if (day < 1 || day > days_in_month) {               /* impossible day?    */
        return 0;                                       /* reject the date    */
    }

    *key = (long)year * 10000L + (long)month * 100L + (long)day; /* sortable  */
    return 1;                                           /* the date is valid  */
}

/*=============================================================================
 * Function : read_line
 * Purpose  : Read one line of any length into fresh memory.
 * Inputs   : stream - the already open file or stdin
 * Output   : a malloc'd string without its newline, which the caller frees, or
 *            NULL at end of file or on an allocation failure
 *
 * [ADDED] (R5) Replaces the generated code's fixed char[512] and fgets.  A
 * longer line used to be delivered in two pieces: the first piece lost its
 * date and was rejected, and the second piece was reported as an unrecognized
 * command, so the email silently disappeared.
 *===========================================================================*/
static char *read_line(FILE *stream)
{
    size_t  capacity = 128;                         /* starting buffer size   */
    size_t  length   = 0;                           /* characters stored      */
    char   *buffer   = (char *)malloc(capacity);    /* first allocation       */
    int     ch;                                     /* one input character    */

    if (buffer == NULL) {                           /* allocation failed?     */
        return NULL;                                /* treat as end of input  */
    }
    ch = fgetc(stream);                             /* read first character   */
    if (ch == EOF) {                                /* nothing left?          */
        free(buffer);                               /* release the buffer     */
        return NULL;                                /* signal end of file     */
    }
    while (ch != EOF && ch != '\n') {               /* until newline or EOF   */
        if (length + 1 >= capacity) {               /* buffer nearly full?    */
            char *grown = (char *)realloc(buffer, capacity * 2); /* double it */
            if (grown == NULL) {                    /* out of memory?         */
                free(buffer);                       /* release what we had    */
                return NULL;                        /* signal failure         */
            }
            buffer    = grown;                      /* keep the larger buffer */
            capacity *= 2;                          /* remember the new size  */
        }
        buffer[length] = (char)ch;                  /* store the character    */
        length++;                                   /* one more character     */
        ch = fgetc(stream);                         /* read the next one      */
    }
    if (length > 0 && buffer[length - 1] == '\r') { /* Windows line ending?   */
        length--;                                   /* drop carriage return   */
    }
    buffer[length] = '\0';                          /* terminate the string   */
    return buffer;                                  /* caller owns this       */
}

/*=============================================================================
 * Function : compare_emails
 * Purpose  : Decide which of two emails the CEO must read first.  This one
 *            function defines the entire ordering of the priority queue.
 * Inputs   : e1, e2 - the two emails being compared
 * Output   : positive if e1 outranks e2, negative if e2 outranks e1
 *
 * [CHANGED] The generated version compared year, month and day as three
 * separate int fields.  Because the date is now stored pre-encoded as
 * YYYYMMDD, that becomes one comparison instead of three, and the encoding
 * makes the newest-first rule impossible to get backwards.  Subtraction is
 * avoided in favour of explicit comparisons so that no difference of two large
 * date keys can overflow.
 *===========================================================================*/
static int compare_emails(const Email *e1, const Email *e2)
{
    if (e1->rank != e2->rank) {                     /* different categories?  */
        return (e1->rank > e2->rank) ? 1 : -1;      /* higher category wins   */
    }
    if (e1->date_key != e2->date_key) {             /* same category, dates?  */
        return (e1->date_key > e2->date_key) ? 1 : -1; /* the NEWER wins      */
    }
    if (e1->sequence != e2->sequence) {             /* same date as well?     */
        return (e1->sequence > e2->sequence) ? 1 : -1; /* later in file wins  */
    }
    return 0;                                       /* the same email         */
}

/*=============================================================================
 * Block: Max Heap Construction & Operations
 *=============================================================================
 * Function : heap_init
 * Purpose  : Put a MaxHeap into a valid, empty state.
 * Inputs   : heap - the heap to initialize
 * Output   : none
 *
 * [CHANGED] (R12, R13) Replaces create_heap, which allocated a second control
 * block and called exit() on failure.  Nothing can fail here, so there is
 * nothing to report and no reason to terminate the program.
 *===========================================================================*/
static void heap_init(MaxHeap *heap)
{
    heap->data     = NULL;          /* no list yet; grown on the first insert */
    heap->size     = 0;             /* the inbox starts empty                 */
    heap->capacity = 0;             /* so it holds zero emails                */
}

/*=============================================================================
 * Function : heap_destroy
 * Purpose  : Release every block of memory the heap owns.
 * Inputs   : heap - the heap to destroy
 * Output   : none
 *
 * [CHANGED] (R9) Also frees each email's subject, which the generated version
 * did not need to do because its subjects lived inside the struct, and which
 * is the one new obligation created by the smaller struct.
 *===========================================================================*/
static void heap_destroy(MaxHeap *heap)
{
    size_t i;                                   /* loop counter               */
    for (i = 0; i < heap->size; i++) {          /* every stored email         */
        free(heap->data[i].subject);            /* free its subject line      */
    }
    free(heap->data);                           /* free the list itself       */
    heap_init(heap);                            /* back to a valid empty state*/
}

/*=============================================================================
 * Function : heap_insert
 * Purpose  : Insert one email, growing the list when it is full and sifting
 *            the new email up to its correct position.
 * Inputs   : heap  - the heap to insert into
 *            email - the email to store; the heap takes ownership of subject
 * Output   : 1 on success, 0 if memory could not be allocated
 *
 * [CHANGED] (R4) The capacity is updated only after realloc succeeds.  The
 * generated code doubled capacity first, so a failed realloc left the heap
 * believing it had room it did not have, and later inserts wrote off the end.
 * [CHANGED] (R10) The sift loop uses the hole technique: the new email is held
 * in a local, parents are shifted down into the gap, and the email is written
 * exactly once at the end.  The generated code performed a three-assignment
 * swap at every level, which is three struct copies per level instead of one.
 * [CHANGED] (R12) Returns a status instead of terminating the program.
 *
 * Complexity: O(log n) time, O(1) auxiliary space; growth is amortized O(1).
 *===========================================================================*/
static int heap_insert(MaxHeap *heap, Email email)
{
    size_t child;                                           /* the moving hole*/

    if (heap->size == heap->capacity) {                     /* the list is full*/
        size_t new_capacity = (heap->capacity == 0)         /* first growth?  */
                              ? INITIAL_CAPACITY            /* start here     */
                              : heap->capacity * 2;         /* else double    */
        Email *grown = (Email *)realloc(heap->data,         /* ask for a bigger*/
                                        new_capacity * sizeof(Email)); /* list*/
        if (grown == NULL) {                                /* failed?        */
            return 0;                                       /* capacity intact*/
        }
        heap->data     = grown;                             /* keep new list  */
        heap->capacity = new_capacity;                      /* now update it  */
    }

    child = heap->size;                                     /* the empty slot */
    heap->size++;                                           /* one more email */
    while (child > 0) {                                     /* until the root */
        size_t parent = (child - 1) / 2;                    /* parent index   */
        if (compare_emails(&email, &heap->data[parent]) <= 0) { /* parent wins*/
            break;                                          /* position found */
        }
        heap->data[child] = heap->data[parent];             /* shift parent   */
        child = parent;                                     /* hole moves up  */
    }
    heap->data[child] = email;                              /* place it once  */
    return 1;                                               /* success        */
}

/*=============================================================================
 * Function : heap_peek_max
 * Purpose  : Look at the highest priority email without removing it.
 * Inputs   : heap - the heap to inspect
 * Output   : pointer to the root email, or NULL when the inbox is empty
 *
 * [CHANGED] (R6, R9) The generated version returned an Email by value with no
 * empty check, so calling it on an empty heap read data[0] regardless.
 * Returning a pointer reports emptiness safely and also avoids copying the
 * struct on every NEXT.
 *===========================================================================*/
static const Email *heap_peek_max(const MaxHeap *heap)
{
    if (heap->size == 0) {          /* nothing stored?                        */
        return NULL;                /* report the empty inbox                 */
    }
    return &heap->data[0];          /* the root is always the next email      */
}

/*=============================================================================
 * Function : heap_extract_max
 * Purpose  : Remove the highest priority email from the queue.
 * Inputs   : heap - the heap to remove from
 *            out  - where to put the removed email, or NULL to discard it and
 *                   free its subject here
 * Output   : 1 if an email was removed, 0 if the inbox was already empty
 *
 * [CHANGED] (R6) Checks for an empty heap instead of trusting the caller; the
 * generated version would have read data[0] and set size to -1.
 * [CHANGED] (R10) Uses the same hole technique as heap_insert, one copy per
 * level instead of three.
 *
 * Complexity: O(log n) time, O(1) auxiliary space.
 *===========================================================================*/
static int heap_extract_max(MaxHeap *heap, Email *out)
{
    Email  moving;                                          /* the last email */
    size_t hole = 0;                                        /* gap at the root*/
    size_t child;                                           /* child index    */

    if (heap->size == 0) {                                  /* empty inbox?   */
        return 0;                                           /* nothing removed*/
    }
    if (out != NULL) {                                      /* caller wants it*/
        *out = heap->data[0];                               /* hand it over   */
    } else {                                                /* caller does not*/
        free(heap->data[0].subject);                        /* so free it here*/
    }
    heap->size--;                                           /* one email fewer*/
    if (heap->size == 0) {                                  /* that was the   */
        return 1;                                           /* only one left  */
    }

    moving = heap->data[heap->size];                        /* hold the last  */
    while ((child = 2 * hole + 1) < heap->size) {           /* while a child  */
        if (child + 1 < heap->size &&                       /* a right child? */
            compare_emails(&heap->data[child + 1],
                           &heap->data[child]) > 0) {       /* stronger one?  */
            child++;                                        /* take the right */
        }
        if (compare_emails(&heap->data[child], &moving) <= 0) { /* it fits here*/
            break;                                          /* position found */
        }
        heap->data[hole] = heap->data[child];               /* shift child up */
        hole = child;                                       /* hole moves down*/
    }
    heap->data[hole] = moving;                              /* place it once  */
    return 1;                                               /* success        */
}

/*=============================================================================
 * Block: Command Parsing and Logic Processing
 *=============================================================================
 * Function : handle_email_command
 * Purpose  : Validate one EMAIL command and add the email to the queue.
 * Inputs   : heap     - the priority queue to insert into
 *            args     - the text following the EMAIL keyword
 *            line_no  - input line number, used in error messages
 *            sequence - running counter used to break exact-date ties
 * Output   : none on stdout; a diagnostic on stderr when the line is rejected
 *
 * [CHANGED] (R7) Splits on the first and last comma instead of using strtok,
 * so a line carrying extra commas is rejected outright rather than silently
 * losing its trailing fields.  Also rejects an empty subject line.
 * [CHANGED] (R9) Allocates the subject to its actual length.
 *===========================================================================*/
static void handle_email_command(MaxHeap *heap, char *args, long line_no, long *sequence)
{
    char  *first_comma;                             /* separates cat/subject  */
    char  *last_comma;                              /* separates subject/date */
    char  *category;                                /* trimmed category text  */
    char  *subject;                                 /* trimmed subject text   */
    char  *date_text;                               /* trimmed date text      */
    Email  email;                                   /* the email being built  */
    int    priority;                                /* the category's rank    */
    size_t subject_length;                          /* length of the subject  */

    if (args == NULL || *args == '\0') {            /* no arguments at all?   */
        fprintf(stderr, "Error (line %ld): EMAIL is missing its arguments. "
                        "Line ignored.\n", line_no);
        return;                                     /* skip this line         */
    }

    first_comma = strchr(args, ',');                /* find the first comma   */
    last_comma  = strrchr(args, ',');               /* find the last comma    */
    if (first_comma == NULL || last_comma == first_comma) { /* fewer than two */
        fprintf(stderr, "Error (line %ld): EMAIL needs the form "
                        "EMAIL <category>,<subject>,<date>. Line ignored.\n",
                line_no);
        return;                                     /* skip this line         */
    }
    if (strchr(first_comma + 1, ',') != last_comma) {   /* more than two?     */
        fprintf(stderr, "Error (line %ld): the subject line may not contain a "
                        "comma. Line ignored.\n", line_no);
        return;                                     /* skip this line         */
    }

    *first_comma = '\0';                            /* cut the category loose */
    *last_comma  = '\0';                            /* cut the date loose     */
    category   = trim_whitespace(args);             /* clean the category     */
    subject    = trim_whitespace(first_comma + 1);  /* clean the subject      */
    date_text  = trim_whitespace(last_comma + 1);   /* clean the date         */

    priority = get_category_priority(category);     /* look up the rank       */
    if (priority == 0) {                            /* not a known category?  */
        fprintf(stderr, "Error (line %ld): invalid sender category \"%s\". "
                        "Line ignored.\n", line_no, category);
        return;                                     /* skip this line         */
    }
    if (*subject == '\0') {                         /* empty subject?         */
        fprintf(stderr, "Error (line %ld): the subject line is empty. "
                        "Line ignored.\n", line_no);
        return;                                     /* skip this line         */
    }
    if (!parse_date(date_text, &email.date_key)) {  /* validate the date      */
        fprintf(stderr, "Error (line %ld): invalid date \"%s\", expected "
                        "MM-DD-YYYY. Line ignored.\n", line_no, date_text);
        return;                                     /* skip this line         */
    }

    subject_length = strlen(subject);               /* exact size needed      */
    email.subject  = (char *)malloc(subject_length + 1); /* right-sized block */
    if (email.subject == NULL) {                    /* out of memory?         */
        fprintf(stderr, "Error (line %ld): out of memory storing the subject "
                        "line. Line ignored.\n", line_no);
        return;                                     /* skip this line safely  */
    }
    memcpy(email.subject, subject, subject_length + 1); /* copy it in         */

    email.rank     = priority;                      /* store the rank         */
    email.sequence = *sequence;                     /* store arrival order    */
    (*sequence)++;                                  /* the next one is newer  */

    if (!heap_insert(heap, email)) {                /* insert into the queue  */
        fprintf(stderr, "Error (line %ld): out of memory growing the inbox. "
                        "Line ignored.\n", line_no);
        free(email.subject);                        /* the heap never took it */
    }
}

/*=============================================================================
 * Function : handle_next_command
 * Purpose  : Display the next email to read, leaving it in the queue so that
 *            two NEXT commands in a row print the same email.
 * Inputs   : heap - the priority queue to inspect
 * Output   : the email block, or a notice that the inbox is empty
 *
 * [CHANGED] (R1) Tab-indents the three detail lines and separates blocks with
 * a blank line, which is what the assignment's sample output requires.
 * [CHANGED] (R9) Rebuilds the printable date from the stored key.
 *===========================================================================*/
static void handle_next_command(const MaxHeap *heap)
{
    const Email *next = heap_peek_max(heap);        /* the highest priority   */
    char date_text[DATE_BUFFER_LEN];                /* scratch for the date   */

    begin_output_block();                           /* blank line if needed   */
    if (next == NULL) {                             /* the inbox is empty?    */
        printf("There are no emails to read.\n");   /* say so plainly         */
        return;                                     /* nothing else to print  */
    }
    format_date(next->date_key, date_text);         /* rebuild MM-DD-YYYY     */
    printf("Next email:\n");                                     /* header    */
    printf("\tSender: %s\n",  SENDER_NAMES[SENDER_COUNT - next->rank]); /* name*/
    printf("\tSubject: %s\n", next->subject);                    /* subject   */
    printf("\tDate: %s\n",    date_text);                        /* date      */
}

/*=============================================================================
 * Function : handle_read_command
 * Purpose  : Record that the CEO read and dealt with the top email by removing
 *            it.  Nothing is displayed, so two READs delete the top two.
 * Inputs   : heap    - the priority queue to remove from
 *            line_no - input line number, used in the warning
 * Output   : none on stdout; a warning on stderr if the inbox is empty
 *===========================================================================*/
static void handle_read_command(MaxHeap *heap, long line_no)
{
    if (!heap_extract_max(heap, NULL)) {            /* try to drop the top    */
        fprintf(stderr, "Warning (line %ld): READ was given but the inbox is "
                        "empty.\n", line_no);       /* warn, do not stop      */
    }
}

/*=============================================================================
 * Function : handle_count_command
 * Purpose  : Display how many unread emails remain.
 * Inputs   : heap - the priority queue to count
 * Output   : one line of the form "There are N emails to read."
 *
 * Note: the wording is fixed by the assignment, so it is printed verbatim and
 * deliberately not pluralized for a count of one.
 *===========================================================================*/
static void handle_count_command(const MaxHeap *heap)
{
    begin_output_block();                           /* blank line if needed   */
    printf("There are %lu emails to read.\n",       /* the required wording   */
           (unsigned long)heap->size);              /* the current count      */
}

/*=============================================================================
 * Function : process_line
 * Purpose  : Identify which command a line holds and dispatch it.
 * Inputs   : heap     - the priority queue the command acts on
 *            line     - the modifiable text of the line
 *            line_no  - input line number, used in error messages
 *            sequence - running counter used to break exact-date ties
 * Output   : whatever the dispatched command prints
 *
 * [CHANGED] (R7) Requires a space or tab after the EMAIL keyword, so a word
 * such as EMAILED is reported as an unknown command rather than being parsed
 * as a malformed EMAIL.
 *===========================================================================*/
static void process_line(MaxHeap *heap, char *line, long line_no, long *sequence)
{
    char *text = trim_whitespace(line);             /* drop outer whitespace  */

    if (*text == '\0') {                            /* a blank line?          */
        return;                                     /* ignore it silently     */
    }
    if (strncmp(text, "EMAIL", 5) == 0 &&           /* starts with the keyword*/
        (text[5] == ' ' || text[5] == '\t')) {      /* and a real separator   */
        handle_email_command(heap, text + 6, line_no, sequence); /* parse it  */
    } else if (strcmp(text, "NEXT") == 0) {         /* the NEXT command       */
        handle_next_command(heap);                  /* show the next email    */
    } else if (strcmp(text, "READ") == 0) {         /* the READ command       */
        handle_read_command(heap, line_no);         /* remove the top email   */
    } else if (strcmp(text, "COUNT") == 0) {        /* the COUNT command      */
        handle_count_command(heap);                 /* print the count        */
    } else if (strcmp(text, "EMAIL") == 0) {        /* EMAIL with no arguments*/
        fprintf(stderr, "Error (line %ld): EMAIL is missing its arguments. "
                        "Line ignored.\n", line_no);
    } else {                                        /* anything else          */
        fprintf(stderr, "Error (line %ld): unrecognized command \"%s\". "
                        "Line ignored.\n", line_no, text);
    }
}

/*=============================================================================
 * Block: Program Entry Point
 *=============================================================================
 * Function : main
 * Purpose  : Open the test file or fall back to standard input, run every
 *            command in it, then release everything.
 * Inputs   : argc, argv - an optional single argument naming the test file
 * Output   : the program's terminal output; EXIT_SUCCESS on a clean run,
 *            EXIT_FAILURE when the input file could not be used
 *
 * [CHANGED] (R8) Accepts a file name on the command line as well as stdin.
 * [CHANGED] (R5) Reads lines into memory that grows instead of a char[512].
 *===========================================================================*/
int main(int argc, char *argv[])
{
    MaxHeap  inbox;                                 /* the CEO's queue        */
    FILE    *input      = stdin;                    /* default input source   */
    int      using_file = 0;                        /* remember to fclose     */
    long     line_no    = 0;                        /* counts input lines     */
    long     sequence   = 0;                        /* counts emails for ties */
    char    *line;                                  /* one line of input      */

    if (argc > 2) {                                 /* too many arguments?    */
        fprintf(stderr, "Usage: %s [testfile]\n", argv[0]); /* show usage     */
        return EXIT_FAILURE;                        /* stop with an error     */
    }
    if (argc == 2) {                                /* a file name was given  */
        input = fopen(argv[1], "r");                /* open it for reading    */
        if (input == NULL) {                        /* missing or unreadable? */
            fprintf(stderr, "Error: cannot open input file \"%s\".\n", argv[1]);
            return EXIT_FAILURE;                    /* stop with an error     */
        }
        using_file = 1;                             /* remember to close it   */
    }

    heap_init(&inbox);                              /* start with an empty one*/

    while ((line = read_line(input)) != NULL) {     /* every line of input    */
        line_no++;                                  /* count it for messages  */
        process_line(&inbox, line, line_no, &sequence); /* dispatch it        */
        free(line);                                 /* release the buffer     */
    }

    if (line_no == 0) {                             /* the input was empty    */
        fprintf(stderr, "Warning: the input contained no commands.\n");
    }

    heap_destroy(&inbox);                           /* free every email       */
    if (using_file) {                               /* a real file was opened?*/
        fclose(input);                              /* close it               */
    }
    return EXIT_SUCCESS;                            /* finished cleanly       */
}
